SELECT * FROM PAYMENT INNER JOIN PAYMENTTYPE on PAYMENTTYPE.ID = PAYMENT.TYPE_ID where NAME = 'MONTHLY';
SELECT * FROM MARK INNER JOIN SUBJECT on MARK.SUBJECT_ID = SUBJECT.ID where name = 'Art';
SELECT * FROM STUDENT INNER JOIN PAYMENT ON PAYMENT.STUDENT_ID = STUDENT.ID INNER JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID where PAYMENTTYPE.NAME = 'WEEKLY';
SELECT * FROM STUDENT INNER JOIN MARK ON MARK.STUDENT_ID = STUDENT.ID INNER JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID where name = 'Math';