SELECT * FROM MARK  where MARK > 6 ORDER BY MARK DESC;
SELECT * FROM payment WHERE amount < 300 ORDER BY amount;
SELECT * FROM PAYMENTTYPE ORDER BY NAME;
SELECT * FROM STUDENT ORDER BY NAME DESC;
SELECT * FROM STUDENT INNER JOIN PAYMENT ON PAYMENT.STUDENT_ID = STUDENT.ID where AMOUNT > 1000 ORDER BY STUDENT.BIRTHDAY;
