insert into Student (id, name, birthday, groupnumber) values (1, 'John', '1974-03-09', 1);
insert into Student (id, name, birthday, groupnumber) values (2, 'Chris', '1975-04-10', 1);
insert into Student (id, name, birthday, groupnumber) values (3, 'Carl', '1976-05-08', 1);
insert into Student (id, name, birthday, groupnumber) values (4, 'Oliver', '1977-05-08', 2);
insert into Student (id, name, birthday, groupnumber) values (5, 'James', '1978-06-08', 2);
insert into Student (id, name, birthday, groupnumber) values (6, 'Lucas', '1979-07-08', 2);
insert into Student (id, name, birthday, groupnumber) values (7, 'Henry', '1980-08-08', 2);
insert into Student (id, name, birthday, groupnumber) values (8, 'Jacob', '1981-10-25', 3);
insert into Student (id, name, birthday, groupnumber) values (9, 'Logan', '1982-09-26', 3);
insert into Student (id, name, birthday, groupnumber) values (10, 'Jane', '1983-10-26', 4);
insert into Student (id, name, birthday, groupnumber) values (11, 'Johanna', '1984-11-26', 4);
insert into Student (id, name, birthday, groupnumber) values (12, 'Anna', '1985-12-26', 5);
insert into Student (id, name, birthday, groupnumber) values (13, 'Hermi', '1986-01-26', 5);
INSERT INTO subject (id, name, grade) VALUES (1, 'Art', 1);
INSERT INTO subject (id, name, grade) VALUES (2, 'Music', 1);
INSERT INTO subject (id, name, grade) VALUES (3, 'Geography', 2);
INSERT INTO subject (id, name, grade) VALUES (4, 'History', 2);
INSERT INTO subject (id, name, grade) VALUES (5, 'PE', 3);
INSERT INTO subject (id, name, grade) VALUES (6, 'Math', 3);
INSERT INTO subject (id, name, grade) VALUES (7, 'Science', 4);
INSERT INTO subject (id, name, grade) VALUES (8, 'IT', 4);
INSERT INTO subject (id, name, grade) VALUES (9, 'Medicine', 5);
INSERT INTO subject (id, name, grade) VALUES (10, 'Law', 5);
insert into PAYMENTTYPE (id, name) values (1, 'DAILY');
insert into PAYMENTTYPE (id, name) values (2, 'WEEKLY');
insert into PAYMENTTYPE (id, name) values (3, 'MONTHLY');
INSERT INTO payment (id, student_id, type_id, amount, payment_date) VALUES (1, SELECT id FROM student WHERE name = 'John', SELECT id FROM paymenttype WHERE name = 'WEEKLY', 5015.45, '2021-02-07 08:09:00');
INSERT INTO payment (id, student_id, type_id, amount, payment_date) VALUES (2, SELECT id FROM student WHERE name = 'Oliver', SELECT id FROM paymenttype WHERE name = 'MONTHLY', 6015.45, '2021-03-07 08:09:00');
INSERT INTO payment (id, student_id, type_id, amount, payment_date) VALUES (3, SELECT id FROM student WHERE name = 'Henry', SELECT id FROM paymenttype WHERE name = 'WEEKLY', 5115.45, '2021-02-08 08:09:00');
INSERT INTO payment (id, student_id, type_id, amount, payment_date) VALUES (4, SELECT id FROM student WHERE name = 'James', SELECT id FROM paymenttype WHERE name = 'DAILY', 7015.45, '2021-02-17 08:09:00');
INSERT INTO payment (id, student_id, type_id, amount, payment_date) VALUES (5, SELECT id FROM student WHERE name = 'Anna', SELECT id FROM paymenttype WHERE name = 'WEEKLY', 4015.45, '2021-01-07 08:09:00');
INSERT INTO payment (id, student_id, type_id, amount, payment_date) VALUES (6, SELECT id FROM student WHERE name = 'Kate', SELECT id FROM paymenttype WHERE name = 'MONTHLY', 8015.45, '2021-02-09 08:09:00');
INSERT INTO mark (mark, student_id, subject_id) VALUES (8, SELECT id FROM student WHERE name = 'Chris', SELECT id FROM subject WHERE name = 'Art');
INSERT INTO mark (mark, student_id, subject_id) VALUES (5, SELECT id FROM student WHERE name = 'Oliver', SELECT id FROM subject WHERE name = 'History');
INSERT INTO mark (mark, student_id, subject_id) VALUES (9, SELECT id FROM student WHERE name = 'James', SELECT id FROM subject WHERE name = 'Geography');
INSERT INTO mark (mark, student_id, subject_id) VALUES (4, SELECT id FROM student WHERE name = 'Jacob', SELECT id FROM subject WHERE name = 'Math');
INSERT INTO mark (mark, student_id, subject_id) VALUES (9, SELECT id FROM student WHERE name = 'Logan', SELECT id FROM subject WHERE name = 'PE');
INSERT INTO mark (mark, student_id, subject_id) VALUES (9, SELECT id FROM student WHERE name = 'Mary', SELECT id FROM subject WHERE name = 'IT');
INSERT INTO mark (mark, student_id, subject_id) VALUES (8, SELECT id FROM student WHERE name = 'Kate', SELECT id FROM subject WHERE name = 'Law');