SELECT MAX(BIRTHDAY) FROM STUDENT;
SELECT MIN(PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK) FROM MARK INNER JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID where DESCRIPTION = 'Math';
SELECT MIN(AMOUNT) FROM PAYMENT INNER JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID where NAME = 'WEEKLY';